# Uses VS Code Rest Client extension
@baseurl = http://localhost:3000/api

### Get all blogs
GET {{baseurl}}/blogs HTTP/1.1

### Get blog by ID
GET {{baseurl}}/blog/7 HTTP/1.1

### Add Blog
POST {{baseurl}}/blogs HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "title": "My New Blog 5",
      "body": "This is the body of the blog post",
      "authorId": 2
    }
}

### Update blog
PUT {{baseurl}}/blogs HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "title": "this blog has been edited",
      "body": "xx oo",
      "id": 21
    }
}

### Delete blog
DELETE {{baseurl}}/blogs HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "id": 23
    }
}

### Search blogs
POST {{baseurl}}/blog/search HTTP/1.1
Content-Type: application/json

{
  "search":
    {
      "term": "apollo"
    }
}









### Post blog
GET {{baseurl}}/blog HTTP/1.1
Content-Type: application/json








### Check if title exists
POST {{baseurl}}/blog/titleCount HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "title": "xxxx"
    }
}


### Delete blog
DELETE {{baseurl}}/blog/delete HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "id": 29
    }
}
